- name: Add host in Zabbix UI
  block:
  - name: Configuring agent in Zabbix server
    ansible.builtin.include_role:
      name: zabbix-server
      tasks_from: agent_config
    vars:
      zabbix_templates: "{{ fmn_zabbix_templates }}"
      zabbix_groups: "{{ fmn_zabbix_groups }}"
  tags:
    - monitoring
  delegate_to: "{{ zabbix_api_srv }}"
  when: zabbix_api_srv is defined

- name: Zabbix check for FMN cert expiry
  ansible.builtin.template:
    src: zabbix-check-fmn-cert.sh.j2
    dest: /usr/lib/zabbix/zabbix-check-fmn-cert.sh
    mode: 0750

- name: Zabbix cron jobs
  ansible.builtin.cron:
    name: FMN Cert monitoring
    job: /usr/lib/zabbix/zabbix-check-fmn-cert.sh
    minute: "0"
